//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize, utoipa :: ToSchema,
)]
#[sea_orm(table_name = "dev_gen_table_column")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub column_id: i64,
    pub table_id: i64,
    pub table_name: String,
    pub column_name: String,
    pub column_comment: String,
    pub column_type: String,
    pub column_key: String,
    pub go_type: String,
    pub go_field: String,
    pub json_field: String,
    pub html_field: String,
    pub is_pk: String,
    pub is_increment: String,
    pub is_required: String,
    pub is_insert: String,
    pub is_edit: String,
    pub is_list: String,
    pub is_query: String,
    pub query_type: String,
    pub html_type: String,
    pub dict_type: String,
    pub sort: u32,
    pub link_table_name: String,
    pub link_table_class: String,
    pub link_table_package: String,
    pub link_label_id: String,
    pub link_label_name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
