//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(
    Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize, utoipa::ToSchema,
)]
#[sea_orm(table_name = "device")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub pid: String,
    pub gid: String,
    pub product_id: String,
    pub device_type: String,
    pub protocol: String,
    pub sn: String,
    pub name: String,
    pub secret: String,
    pub ext: Option<Json>,
    pub ota_version: String,
    pub description: String,
    pub link_status: String,
    pub status: String,
    pub last_link_at: DateTime,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

impl ActiveModelBehavior for ActiveModel {}
