//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(
    Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize, utoipa::ToSchema,
)]
#[sea_orm(table_name = "device_alarm")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub product_id: String,
    pub device_id: String,
    pub name: String,
    pub r#type: String,
    pub level: String,
    pub status: u32,
    #[sea_orm(column_type = "Text")]
    pub content: String,
    pub time: DateTime,
    #[sea_orm(column_type = "Text")]
    pub handle_content: String,
    pub handle_at: Option<DateTime>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

impl ActiveModelBehavior for ActiveModel {}
