//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(
    Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize, utoipa::ToSchema,
)]
#[sea_orm(table_name = "product_schema")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub product_id: String,
    pub classify: String,
    pub name: String,
    pub identifier: String,
    pub r#type: String,
    pub access_mode: String,
    pub required: String,
    pub method: String,
    pub specs: Json,
    pub input_data: Json,
    pub output_data: Json,
    pub description: String,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

impl ActiveModelBehavior for ActiveModel {}
