//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(
    Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize, utoipa::ToSchema,
)]
#[sea_orm(table_name = "series_event")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub ts: DateTime,
    pub ident: String,
    pub event_type: String,
    #[sea_orm(column_type = "Text")]
    pub output_data: String,
    pub product_id: String,
    pub device_id: String,
}

impl ActiveModelBehavior for ActiveModel {}
