//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize, utoipa::ToSchema)]
#[sea_orm(table_name = "series_ts_kv")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub ts: DateTime,
    pub ident: String,
    pub data_type: String,
    pub int_val: Option<i64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub double_val: Option<f64>,
    pub string_val: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub text_val: Option<String>,
    pub product_id: String,
    pub device_id: String,
}

impl ActiveModelBehavior for ActiveModel {}
