//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize, utoipa :: ToSchema,
)]
#[sea_orm(table_name = "series_log")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    pub ts: DateTime,
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub ident_id: String,
    pub trace_id: String,
    pub msg_id: String,
    pub uri: String,
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub content: String,
    pub response: i8,
    pub created_at: DateTime,
    pub product_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
