//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

use crate::enums::Gender;

#[sea_orm::model]
#[derive(
    Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize, utoipa::ToSchema,
)]
#[sea_orm(table_name = "sys_user")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique_key = "uk_username_del")]
    pub username: String,
    pub password: String,
    pub nick_name: String,
    pub phone: String,
    pub avatar: String,
    pub gender: u32,
    pub email: String,
    pub remark: String,
    pub status: String,
    pub create_by: String,
    pub update_by: String,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    #[sea_orm(unique_key = "uk_username_del")]
    pub deleted_at: i64,
}

impl ActiveModelBehavior for ActiveModel {}
