//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(
    Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize, utoipa::ToSchema,
)]
#[sea_orm(table_name = "sys_menu")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub pid: i64,
    pub r#type: String,
    pub name: String,
    pub permission: String,
    pub title: String,
    pub path: String,
    pub icon: String,
    pub component: String,
    pub remark: String,
    pub sort: u32,
    pub visible: String,
    pub is_affix: String,
    pub is_keep_alive: String,
    pub is_iframe: String,
    pub hyperlink: String,
    pub is_sys: String,
    pub status: String,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    pub deleted_at: i64,
}

impl ActiveModelBehavior for ActiveModel {}
