//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize, utoipa :: ToSchema,
)]
#[sea_orm(table_name = "video_channel")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub device_id: i64,
    pub device_no: String,
    pub channel_no: String,
    pub stream_type: String,
    pub url: String,
    pub name: String,
    pub manufacturer: String,
    pub model: String,
    pub owner: String,
    pub civil_code: String,
    pub address: String,
    pub parental: u32,
    pub safety_way: u32,
    pub register_way: u32,
    pub secrecy: u32,
    pub remark: String,
    pub active_at: i64,
    pub status: u32,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
