//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize, utoipa :: ToSchema,
)]
#[sea_orm(table_name = "video_stream")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub device_no: String,
    pub channel_no: String,
    pub r#type: String,
    pub stream_type: String,
    pub stream_id: String,
    pub ssrc: String,
    pub ssrc_seq: u32,
    pub call_id: String,
    pub from_tag: String,
    pub to_tag: String,
    pub cseq_no: u32,
    pub start_at: i64,
    pub end_at: i64,
    pub expire_at: i64,
    pub failure_cnt: u32,
    pub failure_msg: String,
    pub status: u32,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
